from enum import Enum


class StormAlgorithmType(Enum):
    JACOBI = "JACOBI"
    GMM_PLUS_PLUS = "GMM_PLUS_PLUS"
    GAUSS_SEIDEL = "GAUSS_SEIDEL"
    SUCCESSIVE_OVER_RELAXATION = "SUCCESSIVE_OVER_RELAXATION"
    WALKERCHAE = "WALKERCHAE"
    VALUE_ITERATION = "VALUE_ITERATION"
    INTERVAL_ITERATION = "INTERVAL_ITERATION"
    SOUND_VALUE_ITERATION = "SOUND_VALUE_ITERATION"
    OPTIMISTIC_VALUE_ITERATION = "OPTIMISTIC_VALUE_ITERATION"
    RATIONAL_SEARCH = "RATIONAL_SEARCH"
    EIGEN = "EIGEN"
    ELIMINATION = "ELIMINATION"
    ACYCLIC = "ACYCLIC"

    POLICY_ITERATION = "POLICY_ITERATION"
    LINEAR_PROGRAMMING = "LINEAR_PROGRAMMING"
    VALUE_ITERATION_TO_POLICY_ITERATION = "VALUE_ITERATION_TO_POLICY_ITERATION"

    EXPLORATION = "EXPLORATION"
    ABSTRACTION_REFINEMENT = "ABSTRACTION_REFINEMENT"

