from enum import Enum


class StormEngineType(Enum):
    DECISION_DIAGRAM = "DECISION_DIAGRAM"
    SPARSE_MATRICES = "SPARSE_MATRICES"
    DECISION_DIAGRAM_TO_SPARSE_MATRICES = "DECISION_DIAGRAM_TO_SPARSE_MATRICES"
    HYBRID = "HYBRID"
    EXPLORATION = "EXPLORATION"
    ABSTRACTION_REFINEMENT = "ABSTRACTION_REFINEMENT"
